### ISSUE TITLE
Obtaining Fine Location Permissions

### ISSUE THREAD

**Issue by DonEduardo** [vipulasri/LocationUpdates#1]
App works great. Thanks for sharing. Only issue I had was it crashed because app did not have location permissions. Had to go into settings on phone and manually give location permission to the app as the app didn't request it.

**Comment by vipulasri** [comment]
@DonEduardo requiring location permission to enable manually was intentional. As by automatically enabling location services require [SettingsApi ](https://developer.android.com/reference/com/google/android/gms/location/SettingsApi.html) and by using SettingsApi provide result in `onActivityResult()` which is not possible in this case as location service is running in background. 
And In one more case, If we programmatically enable the location permission and user goes to settings, disables the location permission. It will cause unwanted crash.
